#%RAML 1.0
title: switch-request-process-api 
version: v1
baseUri: http://localhost:8081/api/switch-request-process-api/${version}/
protocols: [HTTP]

types: 
  switch_request: !include types/switch_request.raml
  
traits:
   security-header:
      queryParameters:
        client_id:
          type: string
        client_secret:
          type: string


/switchrequest:
  displayName: Switch Request
  description: This resource is used to Switch the connection from one supplier to another.
  
  post:
    is: [security-header] 
    body: 
      application/json:
        type: switch_request
        example: !include examples/switch-request-example.json 
       
    responses: 
      200: 
        body: 
          application/json:
                  
      400:
        body: 
          application/json:
