#%RAML 1.0 DataType
description: Switch Request Datatypes
properties: 
  Customer-Id: string
  Losing-Supplier-Id: string
  Gaining-Supplier-Id: string
  Registration-Request-Id: string
  Meter-Id: string